### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by jcherrabi** [tim-hellhake/cron-adapter#5]
Hello Tim,
can you please add an example of the cron pattern the addon is expecting.. i tried to use *,*,*,* but it kept saying expecting this ^[a-zA-Z]+$ patterns, even copying and pasting this exact patter resulted in an error...

![image](https://user-images.githubusercontent.com/5914393/137602418-9804464c-647d-4c6c-8d49-ee7f833e456c.png)

would be nice to show a simple example pattern in the readme..
thanks.

**Comment by tim-hellhake** [comment]
The error message is about the job title, not the cron expression :smile:

**Comment by tim-hellhake** [comment]
The new version will support numbers in the job name and has an example cron expression in the description.

**Comment by jcherrabi** [comment]
Thanks Tim for the update, but I'm still not clear on how to use? what do you mean by : Go to the things view and add the new cron job. 
I've configured a cron under configuration of the addon, but not sure what to do next.... I've tried to search for new thing nothing came up, i checked under the menu nothing there either, i've checked under rules nothing there. can you please explain how to set a cron job to do something... maybe i didn't understand the concept correctly...
testing this on V:1.0.0 of the gateway

cheers,
Jay

**Comment by tim-hellhake** [comment]
After configuring the cron adapter, there should be at least one new thing if you search for new things.
If not, please attach the logs so I can check if there is an error.
You find them at https://[your gateway]/settings/developer if you click on _View Internal Logs_.

![image](https://user-images.githubusercontent.com/17127122/137812059-c549d0b0-40a3-446b-98dc-07e3115bde63.png)
![image](https://user-images.githubusercontent.com/17127122/137812122-a854c54a-1bfa-4492-8bee-94d6d7bac252.png)
![image](https://user-images.githubusercontent.com/17127122/137812182-0c80a04a-e13a-4342-9792-49b3c57915e2.png)
![image](https://user-images.githubusercontent.com/17127122/137812231-cbcb0c95-4cb1-4fbe-ae84-db8a650a8d95.png)
![image](https://user-images.githubusercontent.com/17127122/137812268-9dfc1c67-07a5-4e64-861f-fe66dcdda84e.png)
![image](https://user-images.githubusercontent.com/17127122/137812304-4ed9d489-cb76-4822-9ac6-562611403134.png)
![image](https://user-images.githubusercontent.com/17127122/137812315-c9bf440d-54fe-4061-8cf2-4f833634b897.png)
![image](https://user-images.githubusercontent.com/17127122/137812341-e434588b-81d0-40bf-8f9a-3ee2859f9345.png)
![image](https://user-images.githubusercontent.com/17127122/137812395-382d5d87-a897-45d5-89fc-d38f8147cde3.png)

**Comment by jcherrabi** [comment]
that's what i thought, but nothing showed up... in the search of things.. here is the log:

2021-10-20 17:31:50.770 INFO   : Loading add-on: cron-adapter
2021-10-20 17:31:55.264 INFO   : cron-adapter: Opening database: /home/pi/.webthings/config/db.sqlite3
2021-10-20 17:31:55.403 INFO   : cron-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/schema.json because it has no messageType
2021-10-20 17:31:59.652 INFO   : cron-adapter: Ignoring https://raw.githubusercontent.com/WebThingsIO/gateway-addon-ipc-schema/master/messages/definitions.json because it has no messageType
2021-10-20 17:32:07.075 INFO   : cron-adapter: Loading add-on cron-adapter from /home/pi/.webthings/addons/cron-adapter
2021-10-20 17:32:07.787 INFO   : cron-adapter: Unhandled Rejection
2021-10-20 17:32:07.793 ERROR  : cron-adapter: Error: Too few fields
2021-10-20 17:32:07.796 ERROR  : cron-adapter:     at CronTime._parse (/home/pi/.webthings/addons/cron-adapter/node_modules/cron/lib/cron.js:418:11)
2021-10-20 17:32:07.798 ERROR  : cron-adapter:     at new CronTime (/home/pi/.webthings/addons/cron-adapter/node_modules/cron/lib/cron.js:46:9)
2021-10-20 17:32:07.800 ERROR  : cron-adapter:     at new CronJob (/home/pi/.webthings/addons/cron-adapter/node_modules/cron/lib/cron.js:565:19)
2021-10-20 17:32:07.802 ERROR  : cron-adapter:     at new CronDevice (/home/pi/.webthings/addons/cron-adapter/lib/cron-adapter.js:35:13)
2021-10-20 17:32:07.805 ERROR  : cron-adapter:     at CronAdapter.<anonymous> (/home/pi/.webthings/addons/cron-adapter/lib/cron-adapter.js:54:34)
2021-10-20 17:32:07.807 ERROR  : cron-adapter:     at Generator.next (<anonymous>)
2021-10-20 17:32:07.809 ERROR  : cron-adapter:     at fulfilled (/home/pi/.webthings/addons/cron-adapter/lib/cron-adapter.js:10:58)
2021-10-20 17:32:11.695 INFO   : About to call startPairing on RunProgramAdapter
2021-10-20 17:32:11.699 INFO   : About to call startPairing on EmailSenderAdapter
2021-10-20 17:32:11.703 INFO   : About to call startPairing on ThingURLAdapter
2021-10-20 17:32:11.707 INFO   : About to call startPairing on CronAdapter
2021-10-20 17:32:11.975 INFO   : Opened a new things socket

![image](https://user-images.githubusercontent.com/5914393/138135924-4bfe5041-9f38-47df-8ec0-cfdef14fd587.png)

**Comment by tim-hellhake** [comment]
> cron-adapter: Error: Too few fields

I think your second cron expression `* * * *` is invalid.

I added a simple regex pattern to highlight those errors in the UI.
Also, there should be a popup with the error message in the UI now if there is something wrong with the cron expression.

**Comment by jcherrabi** [comment]
i confirm that it works now :) thank you.
